apiVersion: batch/v1
kind: Job
metadata:
  name: build-docker-image
spec:
  template:
    spec:
      containers:
      - name: buildkit-container
        image: moby/buildkit:v0.9.0  # Use the BuildKit image
        args:
        - build
        - '--frontend=dockerfile.v0'
        - '--local=context=/workspace'
        - '--local=dockerfile=/workspace/Dockerfile'
        - '--output=type=image,name=harshaweb/daucu:latest,push=true'
        - '/workspace'
        volumeMounts:
        - name: workspace
          mountPath: /workspace
      restartPolicy: Never
      volumes:
      - name: workspace
        emptyDir: {}
